#default: TEST_ENV=http://www1.macys.com -f pretty -f html --out Output_Result.html -f rerun --out rerun.txt

default: TEST_ENV=http://www1.qa11creativemacys.fds.com/ -f pretty -f html --out Output_Result.html -f rerun --out rerun.txt